version: '2'
services:
  dev:
    image: httpd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/local/apache2/htdocs
      - ./node_modules/folhastyle/src/templates/includes/virtual:/usr/local/apache2/htdocs/virtual
      - ./server/httpd-ssi.conf:/usr/local/apache2/conf/httpd.conf
